import type { DotType } from "./types";

export const DOTS_DESKTOP: DotType[] = [
  {
    color: "var(--accent-alpha)",
    top: "8%",
    left: "82%",
    dur: "65s",
    delay: "-5s",
    origin: "-10vw 18vh",
  },
  {
    color: "var(--accent-bravo)",
    top: "7%",
    left: "6%",
    dur: "180s",
    delay: "-6s",
    origin: "-9vw 12vh",
  },
  {
    color: "var(--accent-charlie)",
    top: "35%",
    left: "85%",
    dur: "120s",
    delay: "-8s",
    origin: "14vw -8vh",
  },
  {
    color: "var(--accent-delta)",
    top: "15%",
    left: "70%",
    dur: "140s",
    delay: "-2s",
    origin: "-9vw 12vh",
  },
  {
    color: "var(--accent-echo)",
    top: "52%",
    left: "10%",
    dur: "187s",
    delay: "-3s",
    origin: "-19vw 2vh",
  },
  {
    color: "var(--accent-foxtrot)",
    top: "58%",
    left: "50%",
    dur: "210s",
    delay: "2s",
    origin: "12vw 18vh",
  },
  {
    color: "var(--accent-golf)",
    top: "32%",
    left: "49%",
    dur: "170s",
    delay: "7s",
    origin: "-19vw 2vh",
  },
  {
    color: "var(--accent-hotel)",
    top: "28%",
    left: "20%",
    dur: "155s",
    delay: "-10s",
    origin: "22vw -10vh",
  },
  {
    color: "var(--accent-india)",
    top: "68%",
    left: "35%",
    dur: "200s",
    delay: "11s",
    origin: "-12vw 22vh",
  },
];
